### ISSUE TITLE
Fisherman's Discernment don't work

### ISSUE THREAD

**Issue by CatSpriter** [Huz2e/massmeta#149]
Скилл чип "Fisherman's Discernment" не работает, смотря для примера в лаву нечего не пишется, хотя по описанию скилл чипа должно и писаться что можно поймать и чем поймать.
![image](https://github.com/Huz2e/massmeta/assets/146180293/a08e3667-ef8d-4e80-af8b-63ff8a40d769)
![image](https://github.com/Huz2e/massmeta/assets/146180293/fbc625ed-1628-477c-afe6-6bbc03e21824)

**Comment by homexp13** [comment]
А в других местах должно показывать? Я щас посмотрел оно ни в гидропонике ни в туалете не показывает

**Comment by CatSpriter** [comment]
> А в других местах должно показывать? Я щас посмотрел оно ни в гидропонике ни в туалете не показывает

По идее оно должно показывать везде где можно ловить рыбу, но как видно нам... Оно не работает

**Comment by homexp13** [comment]
на офы фикс залил

**Comment by CatSpriter** [comment]
@homexp13 Или твой фикс не работает или за две недели мы не обновлялись
![Uploading image.png…]()
